apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kubernetes-manifests.yaml

# Patches pentru a adăuga labels Istio (app și version)
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/metadata/labels/version
        value: v1
